from typing import Protocol, runtime_checkable


@runtime_checkable
class ReportStorage(Protocol):
    async def put(self, key: str, data: bytes, content_type: str) -> None: ...
    async def get_presigned_url(self, key: str, expires_in: int = 3600) -> str: ...
    async def delete(self, key: str) -> None: ...
